#!/usr/bin/env python3
"""Embed a .tflite model into the firmware (src/vision/model_data.cc).

    python gen_c_array.py export/tflite/sectornet_s_full_integer_quant.tflite \
                          --version 1

Then rebuild + flash the xiao_s3_vision env. kModelVersion is logged into
every SEC1 record so datasets stay attributable to the model that flew.
"""

import argparse
from pathlib import Path

TEMPLATE = """\
// AUTO-GENERATED by ml/gen_c_array.py — do not edit.
// source: {src}  ({n} bytes, model version {ver})
#include "model_data.h"

const uint8_t g_model_data[] __attribute__((aligned(16))) = {{
{body}
}};
const size_t g_model_data_len = {n};
const uint8_t kModelVersion = {ver};
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tflite")
    ap.add_argument("--version", type=int, required=True,
                    help="model version byte (increment every deployment)")
    ap.add_argument("--out", default=None,
                    help="default: <repo>/src/vision/model_data.cc")
    args = ap.parse_args()

    data = Path(args.tflite).read_bytes()
    out = Path(args.out) if args.out else \
        Path(__file__).resolve().parent.parent / "src/vision/model_data.cc"

    lines = []
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        lines.append(f"    {chunk},")
    out.write_text(TEMPLATE.format(src=Path(args.tflite).name, n=len(data),
                                   ver=args.version, body="\n".join(lines)))
    print(f"wrote {out} ({len(data)} bytes, version {args.version})")
    print("rebuild: pio run -e xiao_s3_vision")


if __name__ == "__main__":
    main()
